name: 03 - Actions - 01

on:
  push:
    branches:
        - main
        - develop

jobs:
  build_and_package:
    runs-on: ubuntu-latest

    env:
      PROD_DB_URL: ${{ secrets.PROD_DB_URL }}
      PROD_DB_USERNAME: ${{ secrets.PROD_DB_USERNAME }}
      PROD_DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
      PROD_SECURITY_PASSWORD: ${{ secrets.PROD_SECURITY_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Java SDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Mostrar branch e versão do Java
        run: |
          echo "Branch atual:"
          git branch
          java --version

      - name: Build com perfil prod
        run: mvn clean package -Dspring.profiles.active=prod

      - name: Build Docker image
        run: |
          docker build \
            --build-arg JAR_FILE=target/coletalixo-0.0.1-SNAPSHOT.jar \
            -t coletalixo-app .
