name: Continuous Integration

on:
  pull_request:
    types: [ opened, reopened ]
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Unit Tests
        run: mvn test